version: '3.7'

services:
    jenkins:
        image: jenkinsci/blueocean
        container_name: jenkins
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        networks:
            - net.io
        volumes:
            - "$PWD/jenkins:/var/jenkins_home"
            - /var/run/docker.sock:/var/run/docker.sock
    sonarqube:
        image: sonarqube
        container_name: sonarqube
        restart: always
        ports:
            - 9000:9000
        networks:
            - net.io
        depends_on:
            - sonardb
        links:
            - sonardb
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
        volumes:
            - "$PWD/sonar/:/var/lib/sonar"
    
    sonardb:
        networks:
            - net.io
        image: postgres:9.6.1
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSTGRESQL_DB=sonar
        ports:
            - "5432:5432"
        volumes:
            - "$PWD/sonardb:/var/lib/postgresql"
    
    nexus:
        image: sonatype/nexus3
        container_name: nexus
        ports:
            - "8081:8081"
        networks:
            - net.io
        volumes:
            - "$PWD/nexus_data:/var/lib/nexus"

networks:
    net.io: