
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GTEQ = 20;
  public static final int MULT = 15;
  public static final int LTEQ = 18;
  public static final int LPAREN = 29;
  public static final int CONTINUE = 4;
  public static final int INT = 9;
  public static final int FOR = 6;
  public static final int MINUS = 14;
  public static final int FLOATLITERAL = 36;
  public static final int RPAREN = 30;
  public static final int OROR = 23;
  public static final int NOT = 25;
  public static final int SEMICOLON = 33;
  public static final int LT = 17;
  public static final int COMMA = 34;
  public static final int DIV = 16;
  public static final int ANDAND = 24;
  public static final int PLUS = 13;
  public static final int IF = 8;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 10;
  public static final int BOOLLITERAL = 37;
  public static final int error = 1;
  public static final int EQEQ = 21;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int EQ = 26;
  public static final int LBRACK = 31;
  public static final int INTLITERAL = 35;
  public static final int LBRACE = 27;
  public static final int ELSE = 5;
  public static final int RBRACK = 32;
  public static final int WHILE = 12;
  public static final int FLOAT = 7;
  public static final int RBRACE = 28;
  public static final int STRINGLITERAL = 38;
  public static final int GT = 19;
  public static final int NOTEQ = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "BREAK",
  "CONTINUE",
  "ELSE",
  "FOR",
  "FLOAT",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "OROR",
  "ANDAND",
  "NOT",
  "EQ",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "INTLITERAL",
  "FLOATLITERAL",
  "BOOLLITERAL",
  "STRINGLITERAL",
  "ID"
  };
}

